export const FETCH_PRODUCTS="FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL="FETCH_PRODUCTS_FAIL";

export const FETCH_CATEGORIES="FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS="FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL="FETCH_CATEGORIES_FAIL";

export const UPDATE_FAVOURITE="UPDATE_FAVOURITE";
export const ADD_TO_CART="ADD_TO_CART";

export const QUANTITY_ADD="QUANTITY_ADD";
export const QUANTITY_SUBTRACT="QUANTITY_SUBTRACT";

export const SET_LOADING="SET_LOADING";

